travelsite/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signup/signup_success/', views.SignUpSuccessView.as_view(), name='signup_success'),
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('profile/<int:pk>/', views.view_profile, name='view_profile_with_pk'),
    path('profile/update/', views.update_profile, name='update_profile'),
]

travelsite/forum/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'forum'

urlpatterns = [
    path('posts/', views.ForumPostListView.as_view(), name='post_list'),
    path('new_post/', views.ForumPostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/<int:pk>/delete/', views.ForumPostDeleteView.as_view(), name='post_delete'),
    #path('post/<int:pk>/comment/', views.CommentCreateView.as_view(), name='comment_create'),
]

travelsite/travelsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePageView.as_view(), name = 'index'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('forum/', include('forum.urls')),
    path('about/', views.AboutView.as_view(), name='about'),
    path('places/', views.PlacesView.as_view(), name='places'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

travelsite/templates/about.html
{% extends "base.html" %}

{% block title %}
<title>About</title>
{% endblock title %}

{% block content %}
<h3>About this site</h3>
<p>This is a site for travelers, by travelers! </p>
<p>Going somewhere? Visit our <a href="{% url 'forum:post_list' %}">forum</a>, where you can ask
questions about future places, and help fellow travelers with their current
journeys!</p>
<p>Need some gear? Head on over to our <a href="#">shop</a>, where you'll find all you need to
get ready for your grand adventure!</p>
<p>Love browsing through photos? Visit our <a href="#">Places</a> page, where
you'll find beautiful, user-submitted photos of Earth's most beautiful places!</p>
<p>Want to submit your own photos? Send them to photos@travelsite.com, and we'll
post them for all to see!</p>
<p>Need an account? You can <a href="{% url 'accounts:signup' %}">sign up here!</a></p>
{% endblock content %}

travelsite/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  {% block title %}
  <title>Travelsite</title>
  {% endblock title %}
  <!-- Bootstrap CSS-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <!-- font -->
  <link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/rawline" type="text/css" />
  <!-- CSS -->
  <link rel="stylesheet" href="\static\css\master.css">
  <!-- Fontawesome CDN -->
  <script src="https://kit.fontawesome.com/6372e07f49.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css "type="text/css">
  {% load static %}
</head>

<body>
  <!-- Navbar -->
  <div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light" class="my-5-5">
    <a class="navbar-brand" href="{% url 'index' %}"><i class="fas fa-compass"></i>TravelSite</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'index' %}">Home<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'places' %}">Places</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="#">Photos</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'forum:post_list' %}">Forum</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'store:product-list' %}">Store</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
        </ul>
        {% if user.is_authenticated %}
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown active">
               <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                 <img class="rounded-circle" id="forumpost_avatar-comment" src="{{request.user.profile.profile_picture.url}}" alt="">  {{request.user.username}}
               </a>
             <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
               <a class="dropdown-item" href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}"><i class="fas fa-user"></i> My Profile</a>
               <a class="dropdown-item" href="#"><i class="fas fa-shopping-cart"></i> Cart</a>
               <a class="dropdown-item" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i> Logout</a>
             </div>
           </li>
          {% else %}
            <a class="btn btn-outline-secndary" href="{% url 'login' %}" role="button"><i class="fas fa-sign-in-alt"></i> Login</a>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  {# /.Navbar #}
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
    {% block content %}
    {% endblock content %}
        </div>
  </div>
  <!-- jQuery CDN -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="{% static 'js/master.js' %}"></script>
  <!-- Popper.js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <!-- Javascript plugins -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

travelsite/templates/index.html
{% extends "base.html" %}
{% block title %}
<title>Home</title>
{% endblock title %}
{% block content %}
<h1>Welcome to TravelSite!</h1>

<div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
        <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
  </div>
</div>
{% endblock content %}